apiVersion: v1
kind: Service
metadata:
  name: doctor-booking-backend-service
spec:
  selector:
    app: doctor-booking-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
